version: 2.1

# Define reusable Docker executor
executors:
  docker-executor:
    docker:
      - image: node:latest
    working_directory: ~/app

# Define environment variables
environment:
  DOCKER_REGISTRY: "docker.io"
  IMAGE_NAME: "rajnages/circleci-app"
  NODE_ENV: "production"
  DOCKER_TAG: "latest"

# Define jobs
jobs:
  building:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: List files after checkout
          command: |
            echo "Listing files in current directory:"
            ls -al
      - run:
          name: Install dependencies
          command: |
            echo "Installing dependencies..."
            cd ~/app  # Ensure this is the correct path
            npm install
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$DOCKER_TAG .

  testing:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            cd ~/app
            npm test

  deploying:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: |
            cd ~/app
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "Pushing Docker image to registry..."
            cd ~/app
            docker push $DOCKER_REGISTRY/$IMAGE_NAME:$DOCKER_TAG
      - run:
          name: Tag Docker image for deployment
          command: |
            cd ~/app
            docker tag $DOCKER_REGISTRY/$IMAGE_NAME:$DOCKER_TAG $DOCKER_REGISTRY/$IMAGE_NAME:$CIRCLE_BRANCH
            docker push $DOCKER_REGISTRY/$IMAGE_NAME:$CIRCLE_BRANCH

# Define workflows
workflows:
  version: 2
  my-workflow:
    jobs:
      - building
      - testing:
          requires:
            - building
      - deploying:
          requires:
            - testing
