version: 2.1

jobs:
  building:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo "Hello world"
  testing:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo "Hello world"
  deploying:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo "Hello world"
workflows:
  my-workflow:
    jobs:
      - building
      - testing
      - deploying
