version: 2.1

# Define reusable Docker executor
executors:
  docker-executor:
    machine: true  # Use machine executor to get access to Docker
    working_directory: ~/app

# Define environment variables
environment:
  DOCKER_REGISTRY: "docker.io"
  IMAGE_NAME: "rajnages/circleci-app"
  NODE_ENV: "production"
  DOCKER_TAG: "latest"

# Define jobs
jobs:
  building:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking files inside folders
          command: |
            echo "Checking files inside folders..."
            ls -l
            cd app && ls -lrta
      - run:
          name: Check Docker username
          command: echo "Docker username is $DOCKER_USERNAME"
      - run:
          name: Install dependencies
          command: |
            cd app
            echo "Installing dependencies..."
            npm install

      - run:
          name: Build Docker image
          command: |
            cd app
            echo "Building Docker image..."
            docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$DOCKER_TAG -f Dockerfile .

  testing:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd app
            echo "Running tests..."
            npm test

  deploying:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: |
            cd app
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            cd app
            echo "Pushing Docker image to registry..."
            docker push $DOCKER_REGISTRY/$IMAGE_NAME:$DOCKER_TAG
      - run:
          name: Tag Docker image for deployment
          command: |
            cd app
            docker tag $DOCKER_REGISTRY/$IMAGE_NAME:$DOCKER_TAG $DOCKER_REGISTRY/$IMAGE_NAME:$CIRCLE_BRANCH
            docker push $DOCKER_REGISTRY/$IMAGE_NAME:$CIRCLE_BRANCH

# Define workflows
workflows:
  version: 2
  my-workflow:
    jobs:
      - building
      - testing:
          requires:
            - building
      - deploying:
          requires:
            - testing
